### ISSUE TITLE
[Server] Checklist entity 생성 및 crud 구현

### ISSUE THREAD

**Issue by pminsung12** [boostcampwm2023/iOS10-OpenList#47]
## 요약
- Checklists resource를 생성하고 crud api 구현

## 체크포인트
- [x] Checklist resource 생성
- [x] crud api 추가
- [x] service 함수 정의
- [x] service.ts 테스트
